trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- bash: 'docker run --rm -e ''AZURE_CLIENT_ID=$(cid)'' -e ''AZURE_SECRET=$(cs)'' -e ''AZURE_SUBSCRIPTION_ID=$(sid)'' -e ''AZURE_TENANT=$(tid)'' -v ''$(Build.SourcesDirectory)/playbooks:/ansible/playbooks''  aleksandarbuza/ansible:latest /ansible/playbooks/playbook.yml'
  displayName: Ansible

